version: '3.1'

services:
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        restart: always
    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        depends_on:
            - zookeeper
        links:
            - zookeeper
        restart: always
        ports:
            - 9092:9092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    nimbus:
        image: storm:2.3.0
        container_name: nimbus
        command: bash -c "storm nimbus && cd /storm-topologies && storm jar target/storm-topologies-1.0.0-jar-with-dependencies.jar com.resulguldibi.storm.samples.KafkaSpoutTopologyMainNamedTopics"
        depends_on:
            - zookeeper
        links:
            - zookeeper
        restart: always
        ports:
            - 6627:6627
        volumes:
            - './nimbus-logs:/logs'
            - './nimbus-data:/data'
            - './nimbus/storm.yaml:/conf/storm.yaml'
            - './storm-topologies:/storm-topologies'
    ui:
        image: storm:2.3.0
        container_name: ui
        command: storm ui
        depends_on:
            - nimbus
        links:
            - nimbus
        restart: always
        ports:
           - 8080:8080
           - 8000:8000
        volumes:
            - './ui-logs:/logs'
            - './ui-data:/data'
            - './ui/storm.yaml:/conf/storm.yaml'
    supervisor:
        image: storm:2.3.0
        container_name: supervisor
        command: storm supervisor
        depends_on:
            - nimbus
            - zookeeper
        links:
            - nimbus
            - zookeeper
            - kafka
        restart: always
        volumes:
            - './supervisor-logs:/logs'
            - './supervisor-data:/data'
            - './supervisor/storm.yaml:/conf/storm.yaml'
#    topology-packager:
#        build: ./topology-packager
#        container_name: topology-submitter
#        command: bash -c "cd /storm-topologies && mvn clean && mvn package"
#        depends_on:
#            - supervisor
#            - nimbus
#            - ui
#        restart: always
#        volumes:
#            - './storm-topologies:/storm-topologies'             
#    topology-submitter:
#        image: storm:2.3.0
#        container_name: topology-submitter
#        command: bash -c "cd /storm-topologies && storm jar target/storm-topologies-1.0.0.jar com.resulguldibi.storm.samples.KafkaSpoutTopologyMainNamedTopics"
#        depends_on:
#            - supervisor
#            - nimbus
#            - ui
#        restart: always
#        volumes:
#            - './topology-submitter-logs:/logs'
#            - './topology-submitter-data:/data'
#            - './storm-topologies:/storm-topologies'            

